- rlbot_gui/gui.py
> Add GameTickPacket listener

- rlbot_gui/gui.py
This will improve accuracy in overlay
> Update the packet more often

- rlbot_gui/bot_management/bot_creation.py
- rlbot_gui/bot_management/downloader.py
Issue is here: #20 
Also includes some quality of life changes.
> Fix creating bots in other drives than $tmp

- rlbot_gui/gui.py
- rlbot_gui/match_runner/match_runner.py
- setup.py
The new port will make us less likely to conflict with other programs. The old one was port 8000 which is very common.
Starting bots after starting the match is the new way of doing things in rlbot 1.15.7, and it will make Self-Driving Car start working.
> Changing port, and starting bots *after* match start

- .gitignore
- rlbot_gui/bot_management/bot_creation.py
- rlbot_gui/bot_management/downloader.py
- rlbot_gui/gui.py
- rlbot_gui/gui/main.html
- setup.py
Bot pack problem: the GUI currently extracts the bot pack and merges the files into the existing bot pack. That could lead to bad consequences:
- Removing a bot from the bot pack won't work
- Renaming a bot in the bot pack will result in both the old and new version being present
- Merging the files could result in broken bots
Complication: It's not safe to clobber the current 'RLBotPack' folder because users could have stored their own bot files there. This is more likely than you think:
- When you download the bot pack, RLBotPack becomes the 'default bot folder'.
- When you choose the 'create new bot' feature, it gets initialized in the default bot folder.
We don't want to delete anybody's stuff, so I'm making a **new** bot pack location called RLBotPackDeletable. RLBotPack will be left …
>  Making the bot pack clobber the previous folder, fixing bugs in bot creation

- rlbot_gui/bot_management/bot_creation.py
- rlbot_gui/gui.py
- rlbot_gui/gui/js/main.js
- rlbot_gui/gui/main.html
- setup.py
- Pulls from https://github.com/RLBot/RLBotScratchInterface/tree/gui-friendly
- Installs webdriver_manager (needed to run scratch bot)
- Respects the user's bot name
- Picks a random port to avoid collisions with other users' bots
> Adding ability to create new scratch bot.

- .gitignore
- rlbot_gui/gui.py
- rlbot_gui/gui/css/style.css
- rlbot_gui/gui/main.html
- setup.py
People can configure bot logos now, either by putting a logo.png next to their bot cfg file, or specifying `logo_file = ...` in their bot cfg like this:
```
[Locations]
looks_config = ./atba_looks.cfg
python_file = atba.py
logo_file = my_logo.png
name = AlwaysTowardsBallAgent
```
> Showing bot logos on the info card.

- rlbot_gui/bot_management/bot_creation.py
- setup.py
This will fix https://github.com/RLBot/RLBotGUI/issues/46
Shortly afterward, I intend to also rename the files in RLBotPythonExample to be more like src/bot.py so people don't feel compelled to rename them.
> Be more flexible and less aggressive with renaming when creating python bots.

- rlbot_gui/gui.py
- rlbot_gui/gui/js/main.js
- rlbot_gui/gui/main.html
- setup.py
This makes the GUI save match settings and team settings when a match is started, and load them on the next startup.
If a bot is no longer valid (`load_bundle` fails), it disappears.
> Remember last match & team settings.

- rlbot_gui/bot_management/downloader.py
- rlbot_gui/gui.py
- rlbot_gui/gui/js/main.js
- rlbot_gui/gui/main.html
- setup.py
This adds a progress bar while downloading the botpack:
The dialog is intentionally non-dismissable, because users shouldn't be starting matches during the download (bot files will get deleted).
I also added checking if there is a newer version of the botpack available, using the GitHub API.
All users will get the snackbar notification when they get this update for the first time, but I think that's alright, because 99% people don't have the latest botpack anyway.
> Download progress bar and checking for botpack updates

- rlbot_gui/gui/css/style.css
- rlbot_gui/gui/js/main.js
- rlbot_gui/gui/main.html
- setup.py
This adds a clearable text field for searching bots by their name, case insensitive.
[![Image from Gyazo](https://i.gyazo.com/f7ff6c1f4af1a666444618f5cec2c30e.gif)](https://gyazo.com/f7ff6c1f4af1a666444618f5cec2c30e)
I also tried removing the bot cards entirely when filtered out, but it was clunky - the Player Types card was resizing too much and the bot logos took a while to load in again. So I think making them just less visible is better.
> Add a 'Filter' field for searching bots

- .gitignore
- MANIFEST.in
- README.md
- setup.py
The problem arises when this happens:
- Developer clones RLBotGUI and starts working on it
- Downloads the bot pack as part of testing
- RLBotGUI copies the bot logos into the gui directory in order to display them
- The logos get included when publishing RLBotGUI to pypi
The download gets filled up with bot logo clutter.
Seems like a good rule to follow is that if you add a new line to .gitignore (which I did) it's also good to consider MANIFEST.in.
> Avoid including bot logos from the bot pack in distributions.

- rlbot_gui/gui/sandbox.vue
- rlbot_gui/type_translation/set_state_translation.py
- setup.py
It's useful for debugging. If you're testing your bot and it does something dumb, you can click rewind and probably see it again. Combined with the freeze feature, this gives you an opportunity to set a breakpoint and really dig into it.
It's a bit janky because:
- It can't literally rewind the clock
- It can't set boost pad state
- If you try to rewind soon after the countdown, the ball may teleport into the goal
- If you try to rewind during a replay, weird stuff will happen
> Adding a rewind button to the sandbox.

- rlbot_gui/gui.py
No longer add an item to the folder settings If no cfg file, or the wrong cfg file, is selected.
> Sanity check for Load Cfg File

- rlbot_gui/gui.py
- rlbot_gui/gui/appearance-editor.vue
- rlbot_gui/gui/main.vue
- rlbot_gui/match_runner/match_runner.py
- setup.py
Let showroom match starter use the selected map on the main screen, instead of just Mannfield. Feature requested by HoveringBanana
> Let showroom use selected map

- pynsist_helpers/upgrade.py
- rlbot_gui/gui.py
- rlbot_gui/upgrade/upgrade_replacer.py
- rlbot_gui/upgrade/upgrade_script.py
- run.py
- setup.py
RLBotGUI installations on windows generally have a file at ./pynsist_helpers/upgrade.py which is NOT part of the rlbot_gui python package. It lives outside the package for the sake of upgrading the package. Unfortunately that means we can't deploy changes to it. Normally users would need to completely reinstall RLBotGUI to get a new version of that file.
This is a hacky way of getting around that. My motivation for doing it right now is I want to use `pipmain(['install', '-r', rlbot_requirements, '--upgrade'])` instead of `pipmain(['install', '-r', rlbot_requirements, '--upgrade', '--upgrade-strategy=eager'])` so we don't obnoxiously upgrade PyQt5 all the time.
Based on my testing, --upgrade still does the vital job of upgrading rlbot and rlbot_gui as expected. If I'm wrong about that, …
> Upgrade script to upgrade the upgrade script.

- rlbot_gui/bot_management/bot_creation.py
- rlbot_gui/gui.py
- rlbot_gui/gui/main.vue
- rlbot_gui/upgrade/upgrade_replacer.py
- setup.py
Hiveminds are the new hot thing. If you're not hivin' you're nothin'.
> Added Python Hivemind to bot creation

- rlbot_gui/gui.py
- rlbot_gui/gui/css/style.css
- rlbot_gui/gui/main.vue
- rlbot_gui/match_runner/match_runner.py
- setup.py
Enable State Setting will be on by default so that Snek, Sniper, and the State Setting Sandbox continue to work.
The others will be off by default.
> Toggles for enable_rendering, enable_state_setting, auto_save_replay.

- rlbot_gui/gui.py
- rlbot_gui/gui/css/style.css
- rlbot_gui/gui/main.vue
- rlbot_gui/match_runner/match_runner.py
- setup.py
The scripts cannot be dragged, only toggled on and off. They are represented by .cfg files just like bots, and can be loaded by file or folder just like bots. You can also click the button next to them to see the metadata pop up.
> Updating the GUI to handle scripts.

- rlbot_gui/gui/main.vue
- setup.py
Message pops up after user clicks on Start Match. Makes people aware that these settings exist, to reduce confusion. Also a useful reminder for people who know about the settings but may have forgotten to change them.
> Calling out rendering and state setting config on match start.

- README.md
- linux-install/README.md
- linux-install/RLBotGUI.sh
It's only been tested on Ubuntu, but it does work there. Any issues that cropped up on my clean VM have been fixed (I'm 90% sure about that) and all additional dependencies (like venv, curl, distutils, and dev) are only installed if they aren't already installed.
The RLBotGUI, in Linux, now lives in `/home/username/.RLBotGUI/`, but the shell script can be put anywhere and it will work.
Read the README for more details.
> Add support for Linux

- rlbot_gui/gui.py
- rlbot_gui/gui/css/style.css
- rlbot_gui/gui/js/story-challenges.js
- rlbot_gui/gui/js/story-mode.js
- rlbot_gui/gui/main.html
Somebody requested a back button, and this felt like the cleanest / most consistent way to do it.
I also fixed the padding on the state setting sandbox so that the ball / cars are aligned correctly with the field image.
> Adding a nav bar to story mode with back btn. Tweaking styling.

- rlbot_gui/story/load_story_descriptions.py
- rlbot_gui/story/story-default.json
- rlbot_gui/story/story_challenge_setup.py
All opponents in the same city have the same primary colors.
All user's teammates use the team color as the secondary color.
Here are the city colors:
- Tryhard: 16, Brown
- Boost: 32, Orange
- Wasteland: 36, Red
- Campandsnipe: 39, Pink
- Championsian: 69, Purplish Red
> Story Mode: Add color matching on teams

- linux-install/README.md
- linux-install/RLBotGUI.sh
Yes, I'm now calling `RLBotGUI.sh` the Linux Installation Shell Script, or LISS for short. (Possible Discord command, `!liss`?)
The full name is RLBotGUI via LISS.
I've fixed the following:
+ Smarter Python 3.7 installation detection
+ The user might not have the `ppa:deadsnakes/ppa` repo, meaning that LISS couldn't install Python 3.7 (https://github.com/deadsnakes)
+ Couldn't install RLBot because psutils was failing to build (this is the reason for `build-essential`)
+ Instead of waiting to see if packages aren't installed, just install them. If they're already installed, then nothing will happen. This way the user won't see a ton of error messages when they first install RLBotGUI via LISS.
+ LISS now runs garbage collection after installing the packages.
+ More noticeable status …
> Updates for the Linux Installation Shell Script (LISS)

- rlbot_gui/story/story-easy.json
2v3 against cryo is a bit hard for Gold/plats which
is what the easy config targets. We turn it
into a 3v3.
We also switch the order so the user has more time
to earn currency before they must recruit the third
teammate.
> Story: Update easy config to have a 3v3 against cryo

- rlbot_gui/story/story-default.json
- rlbot_gui/story/story-easy.json
For default, we add Kamael in the 1v2. Default still uses adversitybot for the 2v2.
For easy, we add Kamael in the 2v2.
Minor unrelated change: Adding city colors to the easy config as well.
> Story: Add Kamael to Heatseeker 

- rlbot_gui/gui/js/story-challenges.js
- rlbot_gui/gui/js/story-mode.js
- rlbot_gui/gui/js/story-upgrades.js
- rlbot_gui/story/story_runner.py
A common problem is that users were buying upgrades before
recruiting teammates after the first match. This resulted
in them being "stuck" where they have to grind before moving
forward.
Another common feedback was that some upgrades were too powerful
and should be more expensive.
This commit adjusts the prices for upgrades and handles both. 
Thanks to @NicEastvillage for additional feedback/ideas on this.
Each match now gives you 2 currency (instead of 1). Recruiting
still costs 1 currency but upgrades have the following costs:
- Boost-33: 3
- Boost-100: 3
- Recharging boost: 4
- Rumble powerups: 6
This means that even after recruiting 1 person, boost-33 can be bought
after the second match. After recruiting 1 more teammate, boost-100 can
be bought after the 4th match.
This is how the …
> Adjust Story Economy

- alternative-install/RLBotGUI.bat
This works better for people who have a space in their username. Formerly it would result in an error like this:
The fix was tested by Homer Star in discord.
> Trying to escape installer unzip command better.

- rlbot_gui/gui/css/style.css
- rlbot_gui/gui/js/main-vue.js
- rlbot_gui/gui/js/mutator-field-vue.js
- setup.py
- Highlight mutators that aren't on their default value, so you can quickly see which ones are active
- If at least one mutator is active, show a badge counting how many are active, so people don't forget to turn them off when they don't want them
> Highlight active mutators & badge with their count

- rlbot_gui/gui/css/style.css
- rlbot_gui/gui/js/bot-card-vue.js
- rlbot_gui/gui/js/main-vue.js
- rlbot_gui/gui/js/team-card-vue.js
- setup.py
- refactored team cards into a component, to eliminate duplicate code
- when there are at least two bots with identical names, find the first parent folder with a unique name (could also be just the agent cfg file) and display it next to the bot names to distinguish them
- works for any number of identical bots
- useful for example for testing different versions against each other
> Distinguish bots with identical names

- pynsist_helpers/rlbot-requirements.txt
I would say that TensorFlow and PyTorch should be added too, but TensorFlow is > 1GB, and PyTorch is finicky.
VirxERLU is small (only 30kb), and I've seen many users get confused at the scary yellow warning next to Abot and VirxEB.
So... pretty please?
> Add VirxERLU-CLib to rlbot-requirements.txt

- rlbot_gui/gui.py
- rlbot_gui/gui/js/main-vue.js
- rlbot_gui/match_runner/custom_maps.py
- rlbot_gui/match_runner/match_runner.py
- rlbot_gui/story/story-default.json
- rlbot_gui/story/story_challenge_setup.py
The long term plans are to create MapPack and leverage it in Story Mode but I think landing this allows us to provide a usable feature and also lets us test out the workflows earlier. It will also be useful for future map makers to easily test out maps with our bots.
A user can do Add -> Add a folder to select a folder with custom maps (`*.upk`) files anywhere in the directory. When the folder is added, the match options settings will show all the custom maps it found with the file suffix. The user can select it and play on it like any other map with/without bots.
We implement the custom map support by "swapping" out the custom map with "Labs_Utopia_P" in the user's RL install directory. As soon as the match is loaded, we swap the original file back to minimize any negative impact.
We …
> Add Support for Custom Maps

- rlbot_gui/gui.py
- rlbot_gui/match_runner/custom_maps.py
- rlbot_gui/match_runner/match_runner.py
This PR adds logic to ignore `*.cfg` files that start with `_`. This in general will allow us to add hidden bots and scripts that can be used in Story Mode without cluttering the UI.
We use this feature to also add script support for custom maps.
> Support "helper scripts" for custom maps

- rlbot_gui/match_runner/custom_maps.py
shutil.move is supposed to raise an exception if the destination
file already exists. However, I didn't run into it in testing
because it is currently a bug in shutil:
https://bugs.python.org/issue42929
So depending on the version of shutil you get, you may or may
not run into this.
The correct implementation is to use os.replace to atomically
delete (if already exists) and move.
> Use os.replace to overwrite existing map file

- rlbot_gui/match_runner/custom_maps.py
This PR adds two minor fixes:
- Custom Maps folders should support maps in the top directory (using `recursive=True`)
- Check if the "folders" key exists before using it to protect against a startup issue
> Custom Maps: Minor fixes

- rlbot_gui/bot_management/downloader.py
- rlbot_gui/gui.py
- rlbot_gui/gui/js/main-vue.js
In order for this to work, RLBot/RLBotPack#118 needs to be committed.
The botpack is currently getting quite big, and not a small portion of our users use RLBot because they have slow internet. So, we should really avoid re-downloading the botpack every time. This is also annoying for people with high-speed internet, as Github limited bandwidth quite a bit - not to mention that unzipping the whole botpack can take a hot second.
This only downloads the required files. Every commit, appveyor makes a release with a zip file called `incremental.zip` - This is all of the changed files in the commit, along with a `.deleted` file that has a list of the deleted files. This zip is many, many times smaller than downloading the whole botpack would be. This results in faster download and extract …
> New super-fast upgrading system

- rlbot_gui/bot_management/downloader.py
- setup.py
I have some minor concerns with changes made to [L0laapk3/RLBotGUI/multithreaded-downloads](https://github.com/L0laapk3/RLBotGUI/tree/multithreaded-downloads).
Mainly that the threads spawned by the pool only serve to initiate and collect the downloads, and it does not make sense to scale them with the number of cpu cores available. All the CPU intensive work is still done on the main thread. For the same reasons it also doesn't make much sense to limit the threshold number of patches before full redownload based on cpu cores available.
The numbers I chose are arbitrary, but I don't think it is a good idea to scale them off of cpu cores.
> Address minor concerns with number of download threads for incremental patching

- rlbot_gui/story/bots-base.json
@Darxeal added an additional bot config that adds a weakness
to blind-and-deaf. This is a bit necessary since a recent
change in blind-and-deaf fixed some quirks which was the only way
to beat blind-and-deaf previously (but also provided for an
inconsistent experience). So hopefully this is a net positive.
I want to wait couple of days to see if any champ-and-up level players can try out
this config and provide some feedback.
> Use story-mode specific version of blind-and-deaf

- .gitignore
- rlbot_gui/bot_management/downloader.py
- rlbot_gui/gui.py
- rlbot_gui/gui/js/main-vue.js
- setup.py
The full workflow for updating the MapPack is this:
- Check if there is a newer release (using the revision number from `index.json`)
- If there is a new release, download the full repo
- Compare old and new `index.json` files 
-  For maps that have an updated revision, download them
This is what the `index.json` file looks like in the map pack:
```json
{
"revision": 3,
"maps": [
{
"path": "Simplicity/Simplicity.upk",
"revision": 3
}
]
}
```
The code leverages some of the existing BotPack downloader logic and makes it more generic for use.
Currently the MapPack is located at [azeemba/RLBotMapPack](https://github.com/azeemba/RLBotMapPack) and here is an example release: [v3](https://github.com/azeemba/RLBotMapPack/releases/tag/v3). This [script …
> Updating and Downloading RLBot MapPack

- rlbot_gui/gui.py
- rlbot_gui/gui/js/main-vue.js
- rlbot_gui/gui/js/story-mode-start.js
- rlbot_gui/gui/js/story-mode.js
- rlbot_gui/match_runner/custom_maps.py
- rlbot_gui/story/load_story_descriptions.py
- rlbot_gui/story/story-default-with-cmaps.json
- rlbot_gui/story/story-easy-with-cmaps.json
- rlbot_gui/story/story_challenge_setup.py
- rlbot_gui/story/story_runner.py
- setup.py
Currently the user facing option to enable custom maps integration is hidden till we update the config to actually use the maps. Since that will take some investigation to find the right maps and bots combo, I think landing this with the option hidden makes the most sense.
Features:
- User option to start story mode with/without "custom maps" support. The option will result in a different story config JSON file being loaded for the story
- Story Mode will detect if the bot pack/map pack are downloaded. If they are missing, the user will be given a button to download them. This will mean new users don't have to know to download the bot pack. They will get prompted to do it.
- For map pack, we will also do a version check. The story config can set a "min" version and if the map pack is …
> Custom Map Integration for Story Mode

- rlbot_gui/gui.py
- rlbot_gui/gui/js/main-vue.js
- setup.py
Javascript is now a official language on the rlbot.org website. Users should be warned when trying to play with a Javascript bot and Node.js isn't installed. The warning looks like the other warnings but with different text.
> Added warning when node isn't installed on Javascript bots.

- rlbot_gui/story/load_story_descriptions.py
- rlbot_gui/story/story_challenge_setup.py
- rlbot_gui/story/story_runner.py
- setup.py
Tested using my own story.json with a script and story-default.json
Currently the "scripts" field is optional in the story json files. Should that be changed?
Also rlbot_to_player_config() and script_to_script_config() share the same first lines but I'm not sure if those lines should be a function instead.
> Scripts Integration for Story Mode

- rlbot_gui/story/story_challenge_setup.py
- setup.py
If the bot team touches the ball before the packet is grabbed in manage_game_state (so before all the bots load in, so when loading 16 bots for example), the last touch for the player team can be None.
This usually doesn't happen because when the while loop runs before a bot touches the ball, the default last touch has attributes team: 0, player_index: 0, so when the packet is loaded, the player team last touch updates, so it's not None.
Also adds a check for player_name to make sure the player actually touched the ball (player_name is an empty string in the default last touch) for a human goal.
To reproduce, put a time.sleep(10) before the while loop and have a bot own-goal.
> Fix AttributeError on Bot Own-Goal

- rlbot_gui/bot_management/downloader.py
- setup.py
Github compression ratio of the botpack is currently 74%, not 65 - so I set it to 75%
The zip file is closer to 60MB than 70MB (it's 54MB)
Return `BotpackStatus.SUCCESS` instead of `True` and `BotpackStatus.REQUIRES_FULL_DOWNLOAD` instead of `False`
This fixes the user continuing to get a prompt that the botpack is out-of-date unless the user does a full download.
> Fix botpack updating

- rlbot_gui/gui.py
- rlbot_gui/gui/css/style.css
- rlbot_gui/gui/js/main-vue.js
- rlbot_gui/match_runner/match_runner.py
- setup.py
- Enabled scripts are now visible regardless of which tab is selected. Resolves #162
- The start match button now has 3 states:
- Launch Rocket League and start match
- Starting match (button is disabled)
- Start another match
This is to hopefully better communicate that RLBot also launches Rocket League but only needs to do that once. Making the button disabled while starting the match prevents people from accidentally clicking it multiple times, and also gives some visual feedback that the app is doing _something_ when the button is clicked.
- Folder settings now have handy buttons to open the folder in explorer. Also refactored a bit.
> Some QoL improvements

- rlbot_gui/gui.py
- setup.py
This will do nothing until the latest version of the installer is published and downloaded.
Adding the flag `--no-warn-script-location` stops Python from warning that Python isn't on the user's PATH, and we know and want that. This change is so no users get scared from the warning.
> Add flag when installing from packages pip to the GUI's Python

- rlbot_gui/gui/js/launcher-preference-vue.js
- rlbot_gui/persistence/settings.py
- setup.py
With the season 4 update, we are now unable to launch Rocket League with the necessary arguments unless we use the "epic login tricks" technique. This used to be opt-in because we were originally not 100% sure it was safe for our users. We've been offering it for a very long time now with no reports of problems, so I consider it to be safe, and it's also the better experience.
I'm removing the choice, and all epic users will go through the login tricks path.
See investigation here: https://discordapp.com/channels/348658686962696195/348659150793736193/876549683466633256
> Making the GUI always use epic login tricks

- rlbot_gui/gui/js/main-vue.js
the weird little CSS rule is because otherwise there's a gap between the radio button group and the new text, and it looks bad
> Add link to languages list in Create Bot dialog

- rlbot_gui/gui/csv/items.csv
- rlbot_gui/gui/js/appearance-editor-vue.js
- rlbot_gui/gui/js/item-field-vue.js
- setup.py
- buttons to randomize items and entire team loadouts
- added latest items
- when clicking the text input of an item, it now gets cleared, so that the entire datalist appears. This is because some users were confused when they clicked an item, for example _Octane_, and only _Octane_ and _Octane ZSR_ showed up. Also it saves you a keyboard press :)
> Randomize buttons in appearance editor

- setup.py
This was a fix to an old issue that NumPy had, it's safe to remove this now and get all of the bug fixes and improvements that come with the newest version. We're currently on version 1.22 and 1.19 is becoming old.
> Remove old NumPy version pin

- rlbot_gui/bot_management/downloader.py
- setup.py
Botpack incremental zips are made in Windows via Powershell.
Powershell and Windows are weird and this results in the files being extracted to the root folder with a name like `RLBotPack\Necto\bot.cfg` instead of being in their proper folders.
This PR just adds an if statement that checks for a non-Windows system and then loops through all the files, renaming them. Works on Linux, at the very least.
ALSO, the script now deletes the `.deleted` file when it's done so it's not lingering around after the upgrade.
> Linux botpack upgrade

- rlbot_gui/bot_management/downloader.py
- setup.py
When the item is a folder and not a file, either a file will be created with the same name or, if the folder already exists, an error will be thrown by `os.rename`. This change fixes that.
> Fix possible error when item is folder

- rlbot_gui/gui.py
- rlbot_gui/gui/js/launcher-preference-vue.js
- rlbot_gui/gui/js/main-vue.js
- rlbot_gui/match_runner/match_runner.py
- rlbot_gui/persistence/settings.py
- setup.py
When people choose epic games, it will not fall back to steam anymore. The default is still the previous behavior, which is now labeled "Try All".
Also had an issue loading RLBotGUI on my system, turns out python's mimetypes lib was assigning text/plain to .js files for some reason. This should fix it for anyone else experiencing the same. This person maybe? https://discordapp.com/channels/348658686962696195/348659150793736193/972629607796842586
> Adding a launcher option for epic only, fixing mime type issue.

- rlbot_gui/gui.py
- rlbot_gui/gui/css/style.css
- rlbot_gui/gui/js/bot-card-vue.js
- rlbot_gui/gui/js/main-vue.js
- rlbot_gui/gui/js/runnable-card-vue.js
- rlbot_gui/gui/js/script-card-vue.js
- rlbot_gui/gui/js/team-card-vue.js
- setup.py
Since some users are oblivious to missing packages warnings
- show compatibility warning modal when such a bot is added to a team
- display info and warning icons on bots in team cards
- hide yellow triangles on bots that are no longer missing packages
Since a decent amount of users are manually selecting BeckwithPark_Midnight, added _(DO NOT SELECT)_ warning next to it
> Better missing packages warnings & more

- rlbot_gui/story/bots-base.json
kamael file name is being renamed to Kamael_family in the botpack. Making these changes so they're up to date.
> update kamael and peter's path

- rlbot_gui/gui.py
- rlbot_gui/gui/js/bot-pool-vue.js
- setup.py
The bot King by CodeRed currently has tags: 
```
tags = 1v1, teamplay,
```
The extra comma results in a empty tag. Since every string contains the empty string, King shows up in all categories.
This fix will make sure we discard tags consisting only of whitespace. Additionally, I changed the category filtering to compare the tags to the entire allowed tag. Before, one tag just had to be a substring of the allowed tag for the bot to be shown.
> [Fix] Fix bug when tags included empty strings

- rlbot_gui/gui/js/community-events-vue.js
- rlbot_gui/gui/js/main-vue.js
- setup.py
> Update events gui

- rlbot_gui/gui/js/story-challenges.js
- rlbot_gui/story/story-default.json
- setup.py
Fixes
- INTRO-2 map changed to Farmstead (BeckwithPark_Dawn does not exist lol)
- You can now recruit bots from mandatory challenges of a city once all the mandatory challenges of that city is complete
> [Fix/Story mode] Fix INTRO-2 map and make adjust recruitment requirements

- rlbot_gui/gui/js/community-events-vue.js
- rlbot_gui/gui/js/main-vue.js
- setup.py
- Better event notifications
- Events happening now and events happening in the future have their own counts and icons
- Most of the time only the future event count/icon will be present, so having the extra distinction when there's something going on _right now_ might be beneficial
- Add support for loading tournament logos
- This will help differentiate at a glance between different tournaments
- Add a "More info" link which will link to the tournament info doc provided in the description of the event
> More community events improvements

- requirements.txt
There is an issue with using greenlet v2+ if you do not have the c++ redistributable installed. it causes an error on trying to start rlbotgui that ends with:
>    from ._greenlet import _C_API # pylint:disable=no-name-in-module
> ImportError: DLL load failed: The specified module could not be found.
The latest gevent pins greenlet to 2+, and rlbotgui has in its requirements to just get any gevent version. So this problem likely has affected some people since the first gevent v22 was pushed to pypi on Oct 8 2022. 
The versions of gevent prior to 22 pin greenlet to be less than 2 - for example in v21.12 it is (<2.0,>=1.1.3)
This fix will pin gevent to be less than v22.
To replicate the issue and test the fix just try to install rlbotgui on any fresh VM or Windows sandbox mode.
> fix greenlet DLL issue

- alternative-install/RLBotGUI.bat
Some users do not have C:\System32 in their PATH environment variable. Ping is in C:\System32 so these users are unable to install the required dependencies using the alternative installer.
All Windows machines are supposed to have ping, so we use an absolute path to it for users that do not have it in their environment variables.
I've tested this alternative installer on my machine with C:\System32 removed from my PATH and it works.
This is a part of #219.
> Use absolute path for ping in alt installer

- alternative-install/RLBotGUI.bat
This fix is the same as the one for the nsi installer but this time for the alternate installer which has its own list of pip commands.
> 
> There is an issue with using greenlet v2+ if you do not have the c++ redistributable installed. it causes an error on trying to start rlbotgui that ends with:
> 
> from ._greenlet import _C_API # pylint:disable=no-name-in-module ImportError: DLL load failed: The specified module could not be found.
> 
> The latest gevent pins greenlet to 2+, and rlbotgui has in its requirements to just get any gevent version. So this problem likely has affected some people since the first gevent v22 was pushed to pypi on Oct 8 2022. The versions of gevent prior to 22 pin greenlet to be less than 2 - for example in v21.12 it is (<2.0,>=1.1.3)
> 
> This fix will pin …
> Fix greenlet issue for the alternate installer

- setup.py
https://github.com/RLBot/RLBot/issues/623 and https://github.com/RLBot/RLBot/issues/627 are related
New minimum Python version is Python 3.11 so older versions of Python install the right packages and we don't break install that might still work
> Fix requirements for Python 3.11

- .appveyor.yml
https://twine.readthedocs.io/en/stable/ says it will read the env variables `TWINE_USERNAME` and `TWINE_PASSWORD` if they're set - use that instead of trying to create a `.pypirc`
> Set twine username/password directly

- rlbot_gui/gui.py
- rlbot_gui/gui/js/bot-card-vue.js
- rlbot_gui/gui/js/bot-pool-vue.js
- rlbot_gui/gui/js/categories.js
- rlbot_gui/gui/js/main-vue.js
- rlbot_gui/gui/js/runnable-card-vue.js
- rlbot_gui/gui/js/script-card-vue.js
- rlbot_gui/persistence/settings.py
- setup.py
Changes:
- Bots and scripts can now be saved as favorites.
- The button to do so is in the info modal. Clicking the button again will remove the bot/script from favorites.
- Favorited bots/scripts show a star next to their name.
- A new Favorites category shows favorited bots/scripts.
Things I'd like a second opinion on:
- Is the favorite button too hidden with its current position (next to name in info modal)? I could move it to the button next to "Edit Appearance".
- Should the star also be displayed on the bot card in the teams?
Please test that this work for you, Mr Reviewer. I don't have many bots/scripts on this computer to test with.
> Add favorites
