RLBot/RLBotGUI

- build-exe.bat
- gui.py
- gui/css/style.css
- gui/js/main.js
- gui/main.html
- run.py
> Support for starting the match, complete with mutators.

- installer.cfg
Fixes one of the problems in #6
> Fixed shortcut can't be pinned to taskbar

- pynsist_helpers/install-and-run.bat
Author: DomNomNom
(Doing it this way as the rebase suggested by tare broke github a little)
Fixes some problems mentioned in #6
> Nicer handling of errors.

- pynsist_helpers/rlbot-requirements.txt
- requirements.txt
- rlbot_gui/bot_management/bot_creation.py
- rlbot_gui/gui.py
- rlbot_gui/gui/js/main.js
- rlbot_gui/gui/main.html
- rlbot_gui/match_runner/match_runner.py
- setup.py
Also includes a few commits that have already been deployed to pypi.
> Documenting the config file editing situation.

- README.md
- installer.cfg
- rlbot_gui/gui.py
- rlbot_gui/gui/css/style.css
- rlbot_gui/gui/js/main.js
- rlbot_gui/gui/main.html
- setup.py
The new shortcut command works for me, and also worked for somebody that had problems with the old one.
> Bot folder management system, plus more reliable shortcut

- rlbot_gui/match_runner/match_runner.py
- setup.py
This is designed to fix https://github.com/RLBot/RLBot/issues/426
> Don't try_receive_agent_metadata unless the setup manager has started.

- installer.cfg
- template.nsi
This removes the page of the installer that allows user to select "Install for everyone" and disables admin right to the installer.
> Remove the multi user selection page.

- rlbot_gui/gui.py
- rlbot_gui/gui/js/main.js
- rlbot_gui/gui/main.html
- rlbot_gui/match_runner/match_runner.py
- setup.py
Added all the options that were missing from gui... This allows start of LAN matches via the new gui...
> Added extra options to the gui.

- README.md
Not sure this is still needed, but removed it.
> Remove the text saying you need to check "Install just for me".

- rlbot_gui/gui.py
- rlbot_gui/gui/css/style.css
- rlbot_gui/gui/js/main.js
- rlbot_gui/gui/main.html
- setup.py
- rearranged buttons in the editor to make it smaller and decreased window height
- editor is scrollable
- added numbers to items with duplicate names (thanks psyoniccs)
- colorpicker highlights selected color
- added button to dismiss botpack update snackbar and made it actually disappear after 10 seconds (that was my intention previously but I messed it up)
> Some fixes and improvements

- rlbot_gui/gui/js/main.js
- setup.py
Related to https://github.com/RLBot/RLBot/issues/436
It's also been seen causing "std exception" coming from RLBot.exe:
> Removing the 'human' player option because it's causing crashes.

- rlbot_gui/gui.py
- rlbot_gui/gui/css/style.css
- rlbot_gui/gui/js/item-field.js
- rlbot_gui/gui/js/main.js
- rlbot_gui/gui/main.html
- setup.py
Added a button to the menu to find and edit an appearance cfg file without having a bot in the GUI. This is handy for me for the Airshow and maybe someone else will also find use for it.
Also fixed my CSS mistake that applied some styles where it shouldn't
> Option to locate and edit an appearance file

- rlbot_gui/gui/sandbox.vue
- rlbot_gui/type_translation/set_state_translation.py
- setup.py
Tested and it works nicely. Rocket League seems to enforce some boundaries behind the scenes. Not sure what they are exactly but it's something on the order of 0.1 to 10.
> Adding a control for setting game speed.

- rlbot_gui/bot_management/downloader.py
- setup.py
Related to https://github.com/RLBot/RLBotPack/pull/41
> Remove Botpack LFS downloading

- rlbot_gui/bot_management/bot_creation.py
Related to previous PR, just forgot to do it before making a pull request.
> Transferred ownership of template to RLBot

- rlbot_gui/gui/css/appearance-editor.css
- rlbot_gui/gui/csv/items.csv
- rlbot_gui/gui/js/appearance-editor-vue.js
- rlbot_gui/gui/js/item-field-vue.js
- setup.py
- new items dumped from BakkesMod, including the new Gravity Bomb explosion
- brought back colored dropdowns
- validation for highlighting invalid item names
> New items & appearance editor improvements

- rlbot_gui/gui/js/appearance-editor-vue.js
- rlbot_gui/gui/js/colorpicker-vue.js
- rlbot_gui/gui/js/story-mode-start.js
Made colorpicker into a vue component to make it more reusable and readable
> Refactor colorpicker into a component

- rlbot_gui/gui/js/story-challenges.js
- rlbot_gui/gui/js/story-mode.js
This allows for easier testing when creating a new story.
You can jump to any city and play any challenge.
You can also change your currency and teammates to test in
whatever combination you need to.
> Add debug mode in Story Mode

- rlbot_gui/gui/css/style.css
- rlbot_gui/gui/js/sandbox-vue.js
- rlbot_gui/gui/js/story-challenges.js
- rlbot_gui/story/bots-base.json
- setup.py
The scroll changes make the story mode handle long lists of challenges nicely.
> Expanding the story mode bot list. Making things scrollable.

- README.md
> Fix image path, bc GitHub auto-renamed the file D:

- rlbot_gui/story/bots-base.json
- rlbot_gui/story/story-default.json
- rlbot_gui/story/story-easy.json
Now that Snek works out of the box and Invisibot is newly added,
we make new additions using these bots. St. Peter is also added
to make some matches more difficult.
Story changes:
- Campandsnipe: 2v3 against Invisibot, Invisibot, St. Peter
- Campandsnipe: 1v2 against Snek, St. Peter
- For easy mode this is 1v2 against Snek, Snek
- Championsian: 2v3 against Snek, Sniper, Invisibot
> Add "Meme" matches in Story Mode

- setup.py
The release is already pushed on both test and main pypi. This is to commit the newer version number.
> Bumping version number to 0.0.77

- rlbot_gui/gui.py
- rlbot_gui/gui/csv/items.csv
- setup.py
- removed printing the "Failed to load recommendations" message because it made some people think that it was the cause of their unrelated issues
- while at it, added some new items
> Removed printing an exception & some new items

- rlbot_gui/gui/js/main.js
Cherry picked and updated from #102 .
> Close GUI when terminal is closed.

- rlbot_gui/gui/js/sandbox-vue.js
- rlbot_gui/gui/js/velocity-arrow-vue.js
- setup.py
[![Image from Gyazo](https://i.gyazo.com/ad6a12e0cca04ede5539553f465c1561.gif)](https://gyazo.com/ad6a12e0cca04ede5539553f465c1561)
I worked on this several months ago, because I planned on making some kind of RLBotTraining integration into the sandbox. But that's a big project and I'm not doing it anytime soon. This feature alone is pretty nice, so I thought it would be worth adding before I completely forget about it.
> Draggable velocity arrows in the sandbox

- alternative-install/RLBotGUI.bat
I've tested this - it correctly identifies when a user is online or offline.
This pings https://rlbot.org/ once, and looks for 'Lost = 0' in the ping command's output.
Fixes RLBot/RLBot#530
> Added check for user's connection to the internet

- rlbot_gui/story/story_challenge_setup.py
There were two different issues with the rendering:
- Sometimes the message wouldn't show up
- Sometimes it would show up but persist into the next match
We fix the first issue by waiting till we are in the new match.
We fix the second issue by creating a rendering group and
clearing the rendering group when a new match starts.
> Story: Fix mercy/failure message rendering

- rlbot_gui/match_runner/custom_maps.py
- rlbot_gui/match_runner/match_runner.py
- setup.py
Steam workshop maps are '.udk' files so this allows you
to add the workshop directly!
> Support '.udk' files for custom maps

- rlbot_gui/gui/js/launcher-preference-vue.js
- setup.py
I think a lot of people are seeing "Epic Login Tricks" and not making the connection to "That's how I get my items." After being DM'd by a new user about it I propose this word change.
> Debatably better wording for the Epic Login Tricks

- rlbot_gui/bot_management/bot_creation.py
- setup.py
Tested by removing my default program for .py files and making a new hivemind and regular python bot. Also tested that it still works with a default program for .py files.
> Fix RLBot/RLBot#548

- rlbot_gui/gui.py
- rlbot_gui/gui/js/main-vue.js
- setup.py
This is a really common problem I see in #issues-and-bugs in the discord server. Instead of users needing to join the discord and ask for help they just see this popup.
> Add a popup in the GUI if trying to start a match when rocket league is opened without -rlbot flag

- rlbot_gui/gui/js/main-vue.js
https://discord.com/channels/348658686962696195/348659150793736193/831221548387270687
> Make the modal that tells the user to close rocket league when not started under the rlbot flag more descriptive.

- rlbot_gui/gui/csv/items.csv
- setup.py
And with proper file encoding!
> Add Season 4 items

- rlbot_gui/gui/js/launcher-preference-vue.js
- setup.py
Numerous users seem to be pasting an incomplete path.
This warns them and _in some cases_ suggests a complete path!
> Warning when path to RocketLeague.exe is incomplete

- rlbot_gui/gui.py
- rlbot_gui/gui/js/launcher-preference-vue.js
- setup.py
also added a print for more information in console screenshots
> Launcher settings bugfix

- rlbot_gui/gui/csv/items.csv
- setup.py
Adds RLCS 2022-23 Esports Shop
> Update items to 2.21

- rlbot_gui/story/bots-base.json
- rlbot_gui/story/load_story_descriptions.py
- rlbot_gui/story/story-default.json
- rlbot_gui/story/story-easy.json
- rlbot_gui/story/story_challenge_setup.py
- rlbot_gui/story/story_runner.py
- setup.py
Also includes various formatting fixes
> Remove Impossibum's bots from story mode

- rlbot_gui/gui/js/community-events-vue.js
- rlbot_gui/gui/js/main-vue.js
- setup.py
Uses the RLBot calendar, same as `!tournaments`.
Functionality by @VirxEC (https://github.com/VirxEC/rlbot_gui_rust/commit/0a9bacf3225f3e52651fef2b2cece82c5432ef3d), refactoring and some styling by me.
> Community events

- rlbot_gui/story/story-default.json
- setup.py
Fixes https://github.com/RLBot/RLBot/issues/609
> Remove Peter from a story match

- rlbot_gui/gui.py
- setup.py
> babe wake up they cahnged the flag name for SOME reason

- rlbot_gui/story/bots-base.json
- rlbot_gui/story/story-default.json
- setup.py
- Register Molten in Story Mode (fixes bug)
- Make match against Invisibot optional (it's hard)
> Fix Story mode missing Molten
